@urlPrefix = http://localhost:9000
@accountId = account-1
@depositId1 = deposit-1
@amount1 = 123.45
@depositId2 = deposit-2
@amount2 = 123.45

### Create a deposit 1

POST {{urlPrefix}}/deposit/{{depositId1}}/create
Content-Type: application/json

{
    "depositId": {
        "accountId": "{{accountId}}",
        "depositId": "{{depositId1}}"
    },
    "amount": {{amount1}}
}

### Create a deposit 2

POST {{urlPrefix}}/deposit/{{depositId2}}/create
Content-Type: application/json

{
    "depositId": {
        "accountId": "{{accountId}}",
        "depositId": "{{depositId2}}"
    },
    "amount": {{amount2}}
}
