@urlPrefix = http://localhost:9000
@accountId = account-1
@withdrawalId = withdrawal-1
@entityId = {{accountId}}_{{withdrawalId}}
@amount = 20.00

### Create a withdrawal

PUT {{urlPrefix}}/withdrawal/{{entityId}}/withdraw
Content-Type: application/json

{
    "withdrawalId": {
        "accountId": "{{accountId}}",
        "withdrawalId": "{{withdrawalId}}"
    },
    "amount": {{amount}}
}

### Get a withdrawal

GET {{urlPrefix}}/withdrawal/{{entityId}}
